# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_album_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='default.png', upload_to=''),
        ),
    ]
